vcf: obs_data/example_six_samples_four_contigs.vcf
popmap: obs_data/popmap_example_1pop.txt
contig_lengths_file: obs_data/contig_length_rec_vs_mut.SNPless_contigs.txt
relative_Ne_distribution: obs_data/example_six_samples_four_contigs.vcf.pi_distr_mean_1.txt

mu: 7.5e-9
rho: 7.5e-9

scenarios:
#   topo.2-1--3: argfiles/3pop/argfile.2-1--3.growth_mig.txt
#   topo.1-3--2: argfiles/3pop/argfile.1-3--2.growth_mig.txt
#   topo.2-3--1: argfiles/3pop/argfile.2-3--1.growth_mig.txt
#   twpop.CM: argfiles/2pop/argfile.CM.twophase_free.twophase_free.txt
#   twpop.OSC: argfiles/2pop/argfile.OSC.twophase_free.twophase_free.txt
#   twpop.PSC: argfiles/2pop/argfile.PSC.twophase_free.twophase_free.txt
#   twpop.SI: argfiles/2pop/argfile.SI.twophase_free.twophase_free.txt
   singlepop: argfiles/1pop/argfile.simple_pop.txt

    
#threepop_topology:
#    "((1,2),3)"
#    "((1,3),2)"
#    "((2,3),1)"    


total_sim_per_scenario: 1000

n_sim_per_chunk: 100

